[build]
  command = "npm run build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"

# Route /api/* to serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[context.production.environment]
  # Frontend uses this to hit the Netlify Functions instead of OpenAI directly
  VITE_API_PROXY = "/api"

